### ISSUE TITLE
crash on opening guide

### ISSUE THREAD

**Issue by jaz3001** [TeamWizardry/TMT-Refraction#17]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/2/17 1:25 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/teamwizardry/refraction/client/jei/JEIRefractionPlugin
	at com.teamwizardry.refraction.common.proxy.RefractionInternalHandler.getStackFromString(RefractionInternalHandler.java:28)
	at com.teamwizardry.refraction.api.book.TextAdapter.convertLinesToString(TextAdapter.java:55)
	at com.teamwizardry.refraction.client.gui.SubPage.<init>(SubPage.java:52)
	at com.teamwizardry.refraction.client.gui.Page.init(Page.java:124)
	at com.teamwizardry.refraction.client.gui.GuiBook.<init>(GuiBook.java:73)
	at com.teamwizardry.refraction.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:19)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
	at com.teamwizardry.refraction.common.item.ItemBook.func_77659_a(ItemBook.java:33)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.teamwizardry.refraction.client.jei.JEIRefractionPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: mezz/jei/api/BlankModPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 27 more
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.BlankModPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.teamwizardry.refraction.common.proxy.RefractionInternalHandler.getStackFromString(RefractionInternalHandler.java:28)
	at com.teamwizardry.refraction.api.book.TextAdapter.convertLinesToString(TextAdapter.java:55)
	at com.teamwizardry.refraction.client.gui.SubPage.<init>(SubPage.java:52)
	at com.teamwizardry.refraction.client.gui.Page.init(Page.java:124)
	at com.teamwizardry.refraction.client.gui.GuiBook.<init>(GuiBook.java:73)
	at com.teamwizardry.refraction.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:19)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
	at com.teamwizardry.refraction.common.item.ItemBook.func_77659_a(ItemBook.java:33)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['jaz3001'/1, l='MpServer', x=11.51, y=4.00, z=14.73]]
	Chunk stats: MultiplayerChunkCache: 552, 552
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,4,8), Chunk: (at 8,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6925 game time, 6925 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['jaz3001'/1, l='MpServer', x=11.51, y=4.00, z=14.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 835171464 bytes (796 MB) / 1889009664 bytes (1801 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	aba{0.101} [Animunda:Black Arts Of The Void] (animunda-1.10.2-0.101.0.jar) 
	UCHIJAAAA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	embers{0.101} [Embers] (embers-0.101.jar) 
	UCHIJAAAA	goetia{0.3.3} [Goetia] (goetia-0.3.3.jar) 
	UCHIJAAAA	librarianlib{1.7} [LibrarianLib] (librarianlib-1.8.jar) 
	UCHIJAAAA	nice{0.0.3} [Nice] (nice-0.0.3.jar) 
	UCHIJAAAA	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCHIJAAAA	refraction{1.3} [Refraction] (refraction-1.3.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	smedry{1.1.1} [Silimatics] (Silimatics-r1.1.1.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	librarianliblate{1.7} [LibrarianLib Stage 2] (librarianlib-1.8.jar) 
	UCHIJAAAA	zml{GRADLE:VERSION.GRADLE:BUILD} [Zen Mod Loader] (ModelMaker-r1.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Launched Version: forge-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3540 @ 2.16GHz

**Comment by LordSaad44** [comment]
Fixed. Will be in the next update. In the meantime: Install JEI
